import { describe,expect,it } from "vitest";
import { buildComparableProjectSummary,buildFounderLearningSnapshot } from "./engine";
import type { LearningProjectRecord } from "./types";

const baseDate="2026-01-01T00:00:00.000Z";
function project(id:number,overrides:Partial<LearningProjectRecord>={}):LearningProjectRecord{return{id:`00000000-0000-4000-8000-${String(id).padStart(12,"0")}`,title:`Project ${id}`,projectType:"saas",status:"validating",lifecycleStatus:"active",createdAt:baseDate,updatedAt:`2026-01-${String(Math.min(28,id+10)).padStart(2,"0")}T00:00:00.000Z`,constraints:{hoursPerWeek:5,budgetBand:"51_to_250",technicalAbility:"recorded_technical_skill",riskTolerance:5},experiments:[],decisions:[],assumptions:[],pathEvents:[],stageEvents:[],lifecycleEvents:[],reflection:null,...overrides};}
function evidence(id:number,replies=1){return{id:`10000000-0000-4000-8000-${String(id).padStart(12,"0")}`,evidenceType:"problem_interview",status:"completed",peopleContacted:5,replies,painConfirmed:replies,interestedUsers:0,waitlistSignups:0,paymentIntent:0,revenueCents:0,createdAt:"2026-01-03T00:00:00.000Z",updatedAt:"2026-01-04T00:00:00.000Z"};}

describe("cross-project learning engine",()=>{
  it("excludes empty, synthetic, and deleted projects from patterns",()=>{const snapshot=buildFounderLearningSnapshot([project(1),project(2,{synthetic:true,experiments:[evidence(2)]}),project(3,{deletedAt:"2026-01-05T00:00:00Z",experiments:[evidence(3)]})]);expect(snapshot.eligibleProjectCount).toBe(0);expect(snapshot.insights).toHaveLength(0);expect(snapshot.projectSummaries.map((item)=>item.eligibility)).toEqual(["ineligible","ineligible","ineligible"]);});
  it("treats a paused project as paused, never completed",()=>{const summary=buildComparableProjectSummary(project(1,{lifecycleStatus:"paused",experiments:[evidence(1)]}));expect(summary.eligibility).toBe("fully_eligible");expect(summary.lifecycleOutcome).toBe("paused");});
  it("does not call one project a repeated validation pattern",()=>{const snapshot=buildFounderLearningSnapshot([project(1,{experiments:[evidence(1)]})]);expect(snapshot.insights.filter((item)=>item.category==="validation")).toHaveLength(0);});
  it("creates a source-linked repeated validation pattern across comparable projects",()=>{const snapshot=buildFounderLearningSnapshot([project(1,{experiments:[evidence(1)]}),project(2,{experiments:[evidence(2)]}),project(3,{experiments:[evidence(3)]})]);const insight=snapshot.insights.find((item)=>item.insightKey==="validation:customer_discovery");expect(insight?.evidenceTier).toBe("repeated_pattern");expect(insight?.supportingProjectIds).toHaveLength(3);expect(insight?.sources.every((item)=>item.sourceKind==="experiment")).toBe(true);expect(insight?.explanation).toMatch(/does not prove/);});
  it("shows contradictory method history instead of hiding it",()=>{const snapshot=buildFounderLearningSnapshot([project(1,{experiments:[evidence(1)]}),project(2,{status:"launched",experiments:[{...evidence(2),replies:0,painConfirmed:0}]}),project(3,{experiments:[evidence(3)]})]);const insight=snapshot.insights.find((item)=>item.insightKey==="validation:customer_discovery");expect(insight?.contradictingProjectIds).toHaveLength(1);expect(insight?.limitations.join(" ")).toMatch(/no recorded external evidence/);});
  it("subtracts paused time from closed stage duration",()=>{const summary=buildComparableProjectSummary(project(1,{experiments:[evidence(1)],stageEvents:[{id:"s1",previousStage:"idea",newStage:"validating",createdAt:"2026-01-11T00:00:00Z"}],lifecycleEvents:[{id:"l1",eventType:"project_paused",createdAt:"2026-01-03T00:00:00Z"},{id:"l2",eventType:"project_resumed",createdAt:"2026-01-08T00:00:00Z"}]}));expect(summary.timeInStages.idea).toBe(5);});
  it("uses only founder-authored closure wording for blocker categories",()=>{const reflection=(id:number)=>({id:`r${id}`,whatWasLearned:"Keep tests smaller.",biggestMistake:"The scope was too big and we overbuilt features.",closureReason:"Stopped after evidence.",wouldDoDifferently:"Reduce scope first.",createdAt:"2026-02-01T00:00:00Z"});const snapshot=buildFounderLearningSnapshot([project(1,{reflection:reflection(1),lifecycleStatus:"abandoned"}),project(2,{reflection:reflection(2),lifecycleStatus:"abandoned"})]);const insight=snapshot.insights.find((item)=>item.insightKey==="blocker:scope_too_large");expect(insight?.supportingProjectIds).toHaveLength(2);expect(insight?.limitations.join(" ")).toMatch(/Keyword categorization/);});
  it("represents repeatedly untested assumptions without saying they are false",()=>{const assumption=(id:number)=>({id:`a${id}`,key:"users_will_pay",status:"untested" as const,updatedAt:"2026-01-04T00:00:00Z"});const snapshot=buildFounderLearningSnapshot([project(1,{experiments:[evidence(1)],assumptions:[assumption(1)]}),project(2,{experiments:[evidence(2)],assumptions:[assumption(2)]})]);const insight=snapshot.insights.find((item)=>item.insightKey==="assumption:willingness_to_pay:untested");expect(insight?.headline).toMatch(/remained untested/);expect(insight?.explanation).toMatch(/does not mean false/);});
  it("phrases decisions as sequence rather than causation",()=>{const decision=(id:number)=>({id:`d${id}`,decisionType:"narrow_audience",createdAt:"2026-01-02T00:00:00Z",experimentId:null});const snapshot=buildFounderLearningSnapshot([project(1,{decisions:[decision(1)],experiments:[evidence(1)]}),project(2,{decisions:[decision(2)],experiments:[evidence(2)]})]);const insight=snapshot.insights.find((item)=>item.insightKey==="decision:narrow_audience");expect(insight?.headline).toMatch(/followed by/);expect(insight?.explanation).toMatch(/does not claim/);});
  it("scales deterministically without creating fake precision",()=>{const projects=Array.from({length:1000},(_,index)=>project(index+1,{experiments:[evidence(index+1)]}));const started=performance.now();const snapshot=buildFounderLearningSnapshot(projects,"2026-12-01T00:00:00Z");expect(performance.now()-started).toBeLessThan(2500);expect(snapshot.insights.some((item)=>item.evidenceTier==="strong_personal_pattern")).toBe(true);expect(JSON.stringify(snapshot)).not.toMatch(/confidence|\b\d{1,3}%/i);});
});
