import { createHash } from "node:crypto";
import { differenceInHours } from "date-fns";
import { evidenceTier, LEARNING_POLICY } from "./policy";
import type { ComparableProjectSummary, FounderLearningSnapshot, FounderPatternCandidate, LearningInsightCategory, LearningProjectRecord, PatternSource } from "./types";

export function buildFounderLearningSnapshot(projects: LearningProjectRecord[], generatedAt = new Date().toISOString()): FounderLearningSnapshot {
  const summaries = projects.map(buildComparableProjectSummary);
  const usable = summaries.filter((item) => item.eligibility !== "ineligible");
  const insights = [
    ...validationInsights(projects,summaries), ...stageInsights(projects,summaries), ...blockerInsights(projects,summaries),
    ...assumptionInsights(projects,summaries), ...decisionInsights(projects,summaries), ...constraintInsights(projects,summaries),
    ...projectTypeInsights(projects,summaries), ...lessonInsights(projects,summaries),
  ].sort((a,b) => tierWeight(b.evidenceTier)-tierWeight(a.evidenceTier) || b.supportingProjectIds.length-a.supportingProjectIds.length || a.headline.localeCompare(b.headline));
  const allDates = projects.flatMap((project) => [project.updatedAt,...project.experiments.map((item)=>item.updatedAt),...project.decisions.map((item)=>item.createdAt)]).filter(Boolean);
  const dataThrough = allDates.sort().at(-1) ?? generatedAt;
  const legacy = summaries.filter((item)=>item.limitations.some((limit)=>/stage history|historical constraint/i.test(limit))).length;
  return {
    generatedAt,dataThrough,eligibleProjectCount:usable.length,
    completedProjectCount:summaries.filter((item)=>item.lifecycleOutcome==="completed").length,
    pausedProjectCount:summaries.filter((item)=>item.lifecycleOutcome==="paused").length,
    stoppedProjectCount:summaries.filter((item)=>item.lifecycleOutcome==="abandoned").length,
    launchedProjectCount:summaries.filter((item)=>item.stageReached==="launched").length,
    revenueProjectCount:summaries.filter((item)=>item.revenueEvidenceCount>0).length,
    projectSummaries:summaries,insights,
    dataQuality:{ sufficientForPatterns:usable.length>=LEARNING_POLICY.minimumPatternProjects, missingSources:[...(projects.every((item)=>!item.reflection)?["No closure reflections have been recorded."]:[]),...(projects.every((item)=>item.assumptions.length===0)?["No structured assumption history is available."]:[])], legacyLimitations:legacy?[`${legacy} project${legacy===1?" is":"s are"} limited for timing or constraint comparisons.`]:[] },
  };
}

export function buildComparableProjectSummary(project: LearningProjectRecord): ComparableProjectSummary {
  const external = project.experiments.reduce((sum,item)=>sum+item.replies+item.painConfirmed+item.interestedUsers+item.waitlistSignups+item.paymentIntent+(item.revenueCents>0?1:0),0);
  const conversations = project.experiments.reduce((sum,item)=>sum+item.peopleContacted,0);
  const methods = unique([...project.pathEvents.map((item)=>item.nextPathType).filter(isText),...project.experiments.map((item)=>methodFromEvidence(item.evidenceType))]);
  const evidenceTypes = unique(project.experiments.filter((item)=>hasExternalEvidence(item)).map((item)=>item.evidenceType));
  const firstEvidence = project.experiments.filter(hasExternalEvidence).sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt))[0];
  const limitations:string[]=[];
  if (!project.stageEvents.length) limitations.push("Stage history is incomplete; this project is excluded from duration comparisons.");
  if (project.constraints.hoursPerWeek==null || !project.constraints.budgetBand) limitations.push("Historical constraint snapshot is incomplete.");
  const blockerCategories = project.reflection ? normalizeBlockers([project.reflection.biggestMistake,project.reflection.closureReason,project.reflection.wouldDoDifferently].filter(isText).join(" ")) : [];
  const assumptionSummary:Record<string,Record<string,number>>={};
  for (const assumption of project.assumptions) { const key=normalizeAssumption(assumption.key); assumptionSummary[key]??={untested:0,supported:0,contradicted:0,inconclusive:0}; assumptionSummary[key][assumption.status]=(assumptionSummary[key][assumption.status]??0)+1; }
  const meaningful = external>0 || project.decisions.length>0 || Boolean(project.reflection) || project.pathEvents.some((item)=>item.eventType==="completed") || project.status==="launched";
  const anyWork = meaningful || project.experiments.length>0 || project.stageEvents.length>0 || project.pathEvents.some((item)=>item.eventType!=="recommended");
  const eligibility = project.synthetic || project.deletedAt || project.excludedAt ? "ineligible" : meaningful ? "fully_eligible" : anyWork ? "partially_eligible" : "ineligible";
  const reason = project.synthetic ? "Synthetic monitoring project." : project.deletedAt ? "Deleted private project." : project.excludedAt ? "Founder excluded this project from learning." : meaningful ? "Contains structured evidence, decisions, closure learning, or a meaningful outcome." : anyWork ? "Contains some structured work but no reliable outcome yet." : "No meaningful founder actions are recorded.";
  return { projectId:project.id,projectTitle:project.title,projectType:project.projectType,eligibility,eligibilityReason:reason,lifecycleOutcome:project.lifecycleStatus,stageReached:highestStage(project),founderConstraints:project.constraints,validationMethods:methods,evidenceTypes,meaningfulDecisionCount:project.decisions.length,experimentCount:project.experiments.length,customerConversationCount:conversations,waitlistSignalCount:sum(project.experiments,"waitlistSignups"),paymentIntentCount:sum(project.experiments,"paymentIntent"),revenueEvidenceCount:project.experiments.filter((item)=>item.revenueCents>0).length,externalEvidenceCount:external,timeToFirstEvidenceDays:firstEvidence?round(Math.max(0,differenceInHours(new Date(firstEvidence.updatedAt),new Date(project.createdAt))/24)):undefined,timeInStages:stageDurations(project),blockerCategories,assumptionSummary,decisionTypes:unique(project.decisions.map((item)=>item.decisionType)),closureReflectionIds:project.reflection?[project.reflection.id]:[],limitations,sourceUpdatedAt:project.updatedAt };
}

function validationInsights(projects:LearningProjectRecord[],summaries:ComparableProjectSummary[]) { const methods=unique(summaries.flatMap((item)=>item.validationMethods)); return methods.flatMap((method)=>{ const used=summaries.filter((item)=>item.eligibility!=="ineligible"&&item.validationMethods.includes(method)); if(used.length<2)return[]; const support=used.filter((item)=>item.externalEvidenceCount>0), contra=used.filter((item)=>item.eligibility==="fully_eligible"&&item.externalEvidenceCount===0); const source:PatternSource[]=[...support.map((item)=>({item,role:"supporting" as const})),...contra.map((item)=>({item,role:"contradicting" as const}))].map(({item,role})=>{const project=projects.find((row)=>row.id===item.projectId)!;const experiment=project.experiments.find((row)=>methodFromEvidence(row.evidenceType)===method);const path=project.pathEvents.find((row)=>row.nextPathType===method);return{projectId:item.projectId,role,sourceKind:experiment?"experiment" as const:path?"validation_path" as const:"project" as const,sourceId:experiment?.id??path?.id??item.projectId};}); return [candidate(`validation:${method}`,"validation",`${label(method)} produced recorded evidence in ${support.length} of ${used.length} projects.`,`This describes recorded external signals after this method was used. It does not prove the method caused the outcome.`,used,support,contra,source,{validation_method:method},contra.length?[`${contra.length} comparable project${contra.length===1?" has":"s have"} no recorded external evidence from this method.`]:["Projects may differ in audience, offer, and execution quality."])]; }); }
function stageInsights(projects:LearningProjectRecord[],summaries:ComparableProjectSummary[]) { const compared=summaries.filter((item)=>item.eligibility!=="ineligible"&&item.timeInStages.building!=null&&item.timeInStages.validating!=null); if(compared.length<2)return[]; const support=compared.filter((item)=>item.timeInStages.building>item.timeInStages.validating*1.5),contra=compared.filter((item)=>!support.includes(item)); if(support.length<2)return[]; return [candidate("stage:building_vs_validating","stage",`Building lasted longer than validation in ${support.length} comparable projects.`,`This is a timing observation. Longer building time is not inherently bad and is not shown as the cause of later outcomes.`,compared,support,contra,projectSources(support,contra),{stage:"building"},["Paused periods were excluded when lifecycle history was available."])]; }
function blockerInsights(projects:LearningProjectRecord[],summaries:ComparableProjectSummary[]) { const categories=unique(summaries.flatMap((item)=>item.blockerCategories)); return categories.flatMap((blocker)=>{ const support=summaries.filter((item)=>item.eligibility!=="ineligible"&&item.blockerCategories.includes(blocker)); if(support.length<2)return[]; const source:PatternSource[]=support.map((item)=>({projectId:item.projectId,role:"supporting",sourceKind:"reflection",sourceId:item.closureReflectionIds[0]??item.projectId})); return [candidate(`blocker:${blocker}`,"blocker",`${label(blocker)} appeared in closure notes across ${support.length} projects.`,`This category comes only from founder-authored closure reflections. PrismForge is not inferring a personality trait or universal cause.`,support,support,[],source,{blocker},["Keyword categorization may miss nuance; open the source projects to review the original reflection."])]; }); }
function assumptionInsights(projects:LearningProjectRecord[],summaries:ComparableProjectSummary[]) { const keys=unique(summaries.flatMap((item)=>Object.keys(item.assumptionSummary))); return keys.flatMap((key)=>{ const relevant=summaries.filter((item)=>item.eligibility!=="ineligible"&&item.assumptionSummary[key]); const untested=relevant.filter((item)=>(item.assumptionSummary[key]?.untested??0)>0); if(untested.length<2)return[]; const tested=relevant.filter((item)=>!untested.includes(item)); const sources:PatternSource[]=projects.flatMap((project)=>project.assumptions.filter((item)=>normalizeAssumption(item.key)===key).map((item)=>{const role:PatternSource["role"]=item.status==="untested"?"supporting":"contradicting";return{projectId:project.id,role,sourceKind:"assumption",sourceId:item.id};})); return [candidate(`assumption:${key}:untested`,"assumption",`${label(key)} remained untested in ${untested.length} projects.`,`Untested does not mean false. It means PrismForge has no recorded test result for this assumption in those projects.`,relevant,untested,tested,sources,{assumption:key},["Automatically routed assumptions may be incomplete in legacy projects."])]; }); }
function decisionInsights(projects:LearningProjectRecord[],summaries:ComparableProjectSummary[]) { const types=unique(projects.flatMap((item)=>item.decisions.map((decision)=>decision.decisionType))); return types.flatMap((type)=>{ const relevant=projects.filter((item)=>item.decisions.some((decision)=>decision.decisionType===type)&&summaries.find((summary)=>summary.projectId===item.id)?.eligibility!=="ineligible"); if(relevant.length<2)return[]; const support=relevant.filter((project)=>project.decisions.some((decision)=>decision.decisionType===type&&project.experiments.some((experiment)=>experiment.updatedAt>decision.createdAt&&hasExternalEvidence(experiment)))); const contra=relevant.filter((item)=>!support.includes(item)); if(!support.length)return[]; const ss=support.map((item)=>summaries.find((summary)=>summary.projectId===item.id)!),cc=contra.map((item)=>summaries.find((summary)=>summary.projectId===item.id)!); const sources:PatternSource[]=relevant.flatMap((project)=>project.decisions.filter((item)=>item.decisionType===type).map((item)=>{const role:PatternSource["role"]=support.includes(project)?"supporting":"contradicting";return{projectId:project.id,role,sourceKind:"decision",sourceId:item.id};})); return [candidate(`decision:${type}`,"decision",`${label(type)} was followed by new external evidence in ${support.length} of ${relevant.length} projects.`,`The sequence is recorded; PrismForge does not claim that the decision caused the later evidence.`,relevant.map((item)=>summaries.find((summary)=>summary.projectId===item.id)!),ss,cc,sources,{decision_type:type},["Subsequent evidence may have been influenced by other changes."])]; }); }
function constraintInsights(projects:LearningProjectRecord[],summaries:ComparableProjectSummary[]) { const low=summaries.filter((item)=>item.eligibility!=="ineligible"&&(item.founderConstraints.hoursPerWeek??99)<=LEARNING_POLICY.lowTimeHoursPerWeek); if(low.length<2)return[]; const support=low.filter((item)=>item.externalEvidenceCount>0),contra=low.filter((item)=>item.eligibility==="fully_eligible"&&item.externalEvidenceCount===0); return [candidate("constraint:low_time","constraint",`Under a recorded five-hour weekly limit, ${support.length} of ${low.length} projects reached external evidence.`,`This describes projects with a similar recorded time constraint. It does not label the founder or predict a future project.`,low,support.length?support:low,contra,projectSources(support.length?support:low,contra),{hours_band:"five_or_less"},["Hours were captured at project creation and may have changed later."])]; }
function projectTypeInsights(projects:LearningProjectRecord[],summaries:ComparableProjectSummary[]) { const types=unique(summaries.map((item)=>item.projectType)); return types.flatMap((type)=>{const compared=summaries.filter((item)=>item.projectType===type&&item.eligibility!=="ineligible");if(compared.length<2)return[];const support=compared.filter((item)=>item.externalEvidenceCount>0),contra=compared.filter((item)=>item.eligibility==="fully_eligible"&&item.externalEvidenceCount===0);return[candidate(`project-type:${type}`,"project_type",`${support.length} of ${compared.length} ${label(type)} projects produced recorded external evidence.`,`This is a descriptive project-type summary, not a claim that this is the founder's best category.`,compared,support.length?support:compared,contra,projectSources(support.length?support:compared,contra),{project_type:type},["Project samples may differ in audience, scope, and maturity."])];}); }
function lessonInsights(projects:LearningProjectRecord[],summaries:ComparableProjectSummary[]) { return projects.filter((item)=>item.reflection&&summaries.find((summary)=>summary.projectId===item.id)?.eligibility!=="ineligible").map((project)=>{const summary=summaries.find((item)=>item.projectId===project.id)!;return candidate(`lesson:${project.id}:${project.reflection!.id}`,"lesson",`A lesson was recorded when ${project.title} closed.`,`This is a founder-authored project lesson, not a recurring pattern or universal conclusion.`,[summary],[summary],[],[{projectId:project.id,role:"supporting",sourceKind:"reflection",sourceId:project.reflection!.id}],{project_type:project.projectType},["One project is not enough to establish a recurring pattern."]);}); }

function candidate(insightKey:string,category:LearningInsightCategory,headline:string,explanation:string,all:ComparableProjectSummary[],support:ComparableProjectSummary[],contra:ComparableProjectSummary[],sources:PatternSource[],dimensions:Record<string,string|number|boolean|null>,limitations:string[]):FounderPatternCandidate { const supportingProjectIds=unique(support.map((item)=>item.projectId)),contradictingProjectIds=unique(contra.map((item)=>item.projectId)); const fingerprint=createHash("sha256").update(JSON.stringify({insightKey,supportingProjectIds:[...supportingProjectIds].sort(),contradictingProjectIds:[...contradictingProjectIds].sort(),sources:sources.map((item)=>`${item.role}:${item.sourceKind}:${item.sourceId}`).sort()})).digest("hex"); const dates=all.map((item)=>item.sourceUpdatedAt).sort(); return{insightKey,category,headline,explanation,evidenceTier:evidenceTier(all.length,supportingProjectIds.length,contradictingProjectIds.length),supportingProjectIds,contradictingProjectIds,sources,limitations,dimensions,evidenceFingerprint:fingerprint,dataThrough:dates.at(-1)??new Date(0).toISOString()}; }
function projectSources(support:ComparableProjectSummary[],contra:ComparableProjectSummary[]):PatternSource[]{return[...support.map((item)=>({projectId:item.projectId,role:"supporting" as const,sourceKind:"project" as const,sourceId:item.projectId})),...contra.map((item)=>({projectId:item.projectId,role:"contradicting" as const,sourceKind:"project" as const,sourceId:item.projectId}))];}
function stageDurations(project:LearningProjectRecord){if(!project.stageEvents.length)return{};const result:Record<string,number>={};const events=[...project.stageEvents].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));let stage="idea",start=new Date(project.createdAt);for(const event of events){const end=new Date(event.createdAt);const hours=Math.max(0,differenceInHours(end,start)-pausedOverlapHours(start,end,project.lifecycleEvents));result[stage]=round((result[stage]??0)+hours/24);stage=event.newStage;start=end;}return result;}
function pausedOverlapHours(start:Date,end:Date,events:LearningProjectRecord["lifecycleEvents"]){const sorted=[...events].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));let pause:Date|null=null,total=0;for(const event of sorted){if(event.eventType==="project_paused")pause=new Date(event.createdAt);if(event.eventType==="project_resumed"&&pause){const from=new Date(Math.max(start.getTime(),pause.getTime())),to=new Date(Math.min(end.getTime(),new Date(event.createdAt).getTime()));if(to>from)total+=differenceInHours(to,from);pause=null;}}if(pause){const from=new Date(Math.max(start.getTime(),pause.getTime()));if(end>from)total+=differenceInHours(end,from);}return total;}
function normalizeBlockers(text:string){const value=text.toLowerCase();const map:Record<string,RegExp>={scope_too_large:/scope|too (big|much)|overbuild|too many feature/,insufficient_time:/not enough time|hours|too busy|time constraint/,audience_unclear:/audience|too broad|niche/,outreach_avoidance:/outreach|interview|talk to|contact user/,pricing_untested:/price|pricing|willing.*pay/,technical_reliability:/technical|code|bug|crash/,acquisition_path_unclear:/acquisition|marketing|channel|find users/,external_dependency:/waiting|dependency|approval/};return Object.entries(map).filter(([,pattern])=>pattern.test(value)).map(([key])=>key);}
function normalizeAssumption(key:string){const value=key.toLowerCase();if(/pay|price/.test(value))return"willingness_to_pay";if(/reach|audience/.test(value))return"audience_reachable";if(/problem|pain/.test(value))return"problem_and_pain";if(/demand/.test(value))return"demand_exists";if(/supply/.test(value))return"supply_exists";if(/solution|useful/.test(value))return"solution_useful";return value.replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")||"other";}
function methodFromEvidence(value:string){const map:Record<string,string>={problem_interview:"customer_discovery",research_pattern:"private_research",prototype_feedback:"prototype_test",landing_page_result:"landing_page_test",waitlist_signup:"waitlist_test",service_pilot_response:"service_pilot",pricing_response:"pricing_test",payment_intent:"pricing_test",content_response:"content_test",marketplace_supply_response:"marketplace_supply_test",marketplace_demand_response:"marketplace_demand_test",physical_product_feedback:"physical_product_test",launch_check:"launch_readiness",post_launch_feedback:"post_launch_learning"};return map[value]??"other";}
function hasExternalEvidence(item:LearningProjectRecord["experiments"][number]){return item.replies+item.painConfirmed+item.interestedUsers+item.waitlistSignups+item.paymentIntent+(item.revenueCents>0?1:0)>0;}
function highestStage(project:LearningProjectRecord){const order=["idea","validating","building","launched"];return[project.status,...project.stageEvents.map((item)=>item.newStage)].sort((a,b)=>order.indexOf(b)-order.indexOf(a))[0]??project.status;}
function sum(items:LearningProjectRecord["experiments"],key:"waitlistSignups"|"paymentIntent"){return items.reduce((total,item)=>total+item[key],0);}
function unique<T>(items:T[]){return Array.from(new Set(items));} function isText(value:unknown):value is string{return typeof value==="string"&&value.length>0;} function round(value:number){return Math.round(value*10)/10;} function label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());} function tierWeight(value:string){return value==="strong_personal_pattern"?3:value==="repeated_pattern"?2:1;}
